### ISSUE TITLE
About the visualizations of the paper

### ISSUE THREAD

**Issue by MAX-OTW** [leftthomas/DaCo#1]
Hi , @leftthomas @zhengziqiang @yangwu-jp  ，-I really appreciate for your work！Congratulations :)
The visualizations(Fig. 6 The feature distribution visualization of various methods by using T-SNE on these datasets)in the paper look great.Currently I want to try to implement them but I failed. Is it convenient to provide the relevant implementation code?Of course, detailed guidance would be better.

I am always looking forward to your kind response.
Best regards.

**Comment by leftthomas** [comment]
@MAX-OTW you could refer `seaborn` library to find how to draw `T-SNE` images
